src/csvs/urls.py
from django.urls import path
from .views import upload_file_view

app_name = 'csvs'

urlpatterns = [
    path('', upload_file_view, name='upload-view'),
]

src/customers/urls.py
from django.urls import path
from .views import customer_corr_view

app_name = 'customers'

urlpatterns = [
    path('', customer_corr_view, name='main-customers-view'),
]

src/ds_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home_view, login_view, register_view

from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('performance/', include('products.urls', namespace='products')),
    path('upload/', include('csvs.urls', namespace='csvs')),
    path('customers/', include('customers.urls', namespace='customers')),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path
from .views import chart_select_view, add_purchase_view, sales_dist_view


app_name = 'products'

urlpatterns = [
    path('', chart_select_view, name='main-products-view'),
    path('add/', add_purchase_view, name='add-purchase-view'),
    path('salesman/', sales_dist_view, name='sales-view'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--jQuery-->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
    <!--Custom css-->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!--Semantic UI-->
    <link rel="stylesheet" type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.min.js"></script>

    <title>Django Pandas Project - {% block title %}{% endblock title %}</title>
</head>
<body>
{% include 'navbar.html' %}
<div class="ui container">

        {% if messages %}
        {% for message in messages %}
        <div class="ui {{ message.tags }} message">
            <i class="close icon"></i>
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}

    {% block content %}
    {% endblock content %}
</div>

<script type="text/javascript" src="{% static 'main.js' %}"></script>
<!--type="text/javascript"-->
</body>
</html>

src/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Home page {% endblock title %}

{% block content %}
<div class="block-center">
    <h2>Data Analysis Center</h2>
    <img src="{% static 'main_pic.jpg' %}" class="ui fluid image mtop">
</div>
{% endblock content %}

src/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
<!--{% load static %}-->
{% block title %} Login page {% endblock title %}

{% block content %}
{% if error_message %}
<div class="ui negative message">
    <i class="close icon"></i>
    <div class="header">
        {{ error_message }}
    </div>
</div>
{% endif %}
<h2>Login</h2>
<div class="block-center">
    <form action="" method="POST" class="ui form">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="ui button positive mtop">Login</button>
    </form>
    <div class="mtop">
    <small class="text-muted mtop">Need An Accout?
        <a href="{% url 'register' %}">Sign Up Now</a></small>
    </div>
</div>
{% endblock content %}

src/templates/logout.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Login page {% endblock title %}

{% block content %}
    <h2>You have been logged out</h2>
    <a href="{% url 'login' %}">Log In Again</a>
{% endblock content %}

src/templates/navbar.html
{% url 'home' as path_to_home %}
{% url 'login' as path_to_login %}
{% url 'register' as path_to_register %}
{% url 'logout' as path_to_logout %}
{% url 'products:main-products-view' as path_to_performance %}
{% url 'products:add-purchase-view' as path_to_adding_records %}
{% url 'csvs:upload-view' as path_to_upload %}
{% url 'customers:main-customers-view' as path_to_customers %}
{% url 'products:sales-view' as path_to_sales %}


<div class="ui secondary pointing menu">
    <a href="{{ path_to_home }}" class="{% if request.path == path_to_home %}active{% endif %} item">
        Home
    </a>
    {% if request.user.is_authenticated %}
    <a href="{{ path_to_performance }}" class="{% if request.path == path_to_performance %}active{% endif %} item">
        Performance
    </a>
    <a href="{{ path_to_sales }}" class="{% if request.path == path_to_sales %}active{% endif %} item">
        Sales
    </a>
    <a href="{{ path_to_customers }}" class="{% if request.path == path_to_customers %}active{% endif %} item">
        Customers
    </a>
    <a href="{{ path_to_adding_records }}"
       class="{% if request.path == path_to_adding_records %}active{% endif %} item">
        Add records
    </a>
    <a href="{{ path_to_upload }}" class="{% if request.path == path_to_upload %}active{% endif %} item">
        Upload file
    </a>
    <div class="right menu">
        <a href="{{ path_to_logout }}" class="ui item {% if request.path == path_to_logout %}active{% endif %}">
            Logout
        </a>
    </div>
    {% else %}
    <div class="right menu">
        <a href="{{ path_to_login }}" class="ui item {% if request.path == path_to_login %}active{% endif %}">
            Login
        </a>
        <a href="{{ path_to_register }}" class="ui item {% if request.path == path_to_register %}active{% endif %}">
            Register
        </a>
    </div>
    {% endif %}

</div>

src/templates/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %} Login page {% endblock title %}

{% block content %}
<h2>Join Now</h2>
<div class="block-center">
    <form action="" method="POST" class="ui form">
        {% csrf_token %}
<!--        {{ form.as_p }}-->
        {{ form|crispy }}
        <button type="submit" class="ui button positive mtop">Sign Up</button>
        <div class="mtop">
            <small class="text-muted">Already Have An Accout?
                <a href="{% url 'login' %}">Sign In</a></small>
        </div>
    </form>
</div>
{% endblock content %}